workflows:
  react-native-ios-basic:
    name: React Native iOS (Básico)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        BUNDLE_ID: "io.github.vinicius-quadros.hammer"
        XCODE_WORKSPACE: "Hammer.xcworkspace"
        XCODE_SCHEME: "Hammer"
    scripts:
      - name: Instalar dependências npm
        script: |
          npm install
          
      - name: Instalar pods
        script: |
          cd ios && pod install

      - name: Compilar para iOS (Debug)
        script: |
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Debug -sdk iphonesimulator build
    artifacts:
      - /tmp/xcodebuild_logs/*.log